package repository_test

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/open-workout/ow/internal/domain"
	"github.com/open-workout/ow/internal/infrastructure/repository"
	"github.com/testcontainers/testcontainers-go/modules/postgres"

	_ "github.com/lib/pq"
)

func setupTestDB(t *testing.T) (*sql.DB, func()) {
	ctx := context.Background()

	container, err := postgres.Run(ctx,
		"postgres:15",
		postgres.WithDatabase("test_db"),
		postgres.WithUsername("test_user"),
		postgres.WithPassword("test_password"),
	)
	if err != nil {
		t.Fatalf("Failed to start container: %v", err)
	}

	connStr, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		t.Fatalf("Failed to get connection string: %v", err)
	}

	db, err := sql.Open("postgres", connStr)
	if err != nil {
		t.Fatalf("Failed to connect: %v", err)
	}

	// IMPORTANT: retry loop instead of single ping
	deadline := time.Now().Add(10 * time.Second)

	for {
		err = db.Ping()
		if err == nil {
			break
		}

		if time.Now().After(deadline) {
			t.Fatalf("DB not ready: %v", err)
		}

		time.Sleep(200 * time.Millisecond)
	}

	cleanup := func() {
		err := db.Close()
		if err != nil {
			t.Fatalf("Failed to close DB: %v", err)
		}

		err = container.Terminate(ctx)
		if err != nil {
			t.Fatalf("Failed to terminate container: %v", err)
		}
	}

	return db, cleanup
}

func setupSchema(t *testing.T, db *sql.DB) {
	queries := []string{
		`CREATE TABLE workouts (
			workout_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id INT NOT NULL,
			started_at TIMESTAMP NOT NULL,
			finished_at TIMESTAMP
		);`,
		`CREATE TABLE workout_sets (
			workout_id INT,
			exercise_id INT,
			reps INT,
			difficulty INT,
			weight DOUBLE PRECISION,
			logged_at TIMESTAMP
		);`,
	}

	for _, q := range queries {
		if _, err := db.Exec(q); err != nil {
			t.Fatalf("schema error: %v\nquery: %s", err, q)
		}
	}
}

// ----------------------------------
// WORKOUT tests
// ----------------------------------

func TestCreateWorkout_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)

	repo := repository.NewSqlRepository(db)

	workout := &domain.WorkoutModel{
		WorkoutID: 100,
		UserID:    1,
	}

	_, err := repo.CreateWorkout(context.Background(), workout)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	var count int
	err = db.QueryRow("SELECT COUNT(*) FROM workouts").Scan(&count)
	if err != nil {
		t.Fatalf("Failed to get workouts: %v", err)
	}
	if count != 1 {
		t.Fatalf("Wrong number of workouts: %d", count)
	}

	var insertedUserID int
	err = db.QueryRow("SELECT  user_id FROM workouts WHERE workout_id = $1", workout.WorkoutID).Scan(&insertedUserID)
	if err != nil {
		t.Fatalf("Failed to get workout: %v", err)
	}
	if insertedUserID != workout.UserID {
		t.Fatalf("Wrong workout WorkoutID: %d", insertedUserID)
	}
}

// ----------------------------------
// SET tests
// ----------------------------------

func TestAllowsSetsWithSameWorkoutIDAndExerciseID_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)
	set1 := &domain.SetModel{
		WorkoutID:  100,
		ExerciseID: 1,
		Reps:       1,
		Difficulty: 2,
		Weight:     3,
		LoggedAt:   time.Now(),
	}

	set2 := &domain.SetModel{
		WorkoutID:  100,
		ExerciseID: 1,
		Reps:       1,
		Difficulty: 2,
		Weight:     3,
		LoggedAt:   time.Now(),
	}

	_, err := repo.CreateSet(context.Background(), set1)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	_, err = repo.CreateSet(context.Background(), set2)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	var count int
	err = db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE workout_id=100 AND exercise_id=1").Scan(&count)

	if count != 2 {
		t.Fatalf("Wrong number of sets: %d", count)
	}
}

func TestCreateSet_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)

	repo := repository.NewSqlRepository(db)
	workoutSet := &domain.SetModel{
		WorkoutID:  100,
		ExerciseID: 1,
		Reps:       10,
		Difficulty: 7,
		Weight:     80,
		LoggedAt:   time.Now(),
	}

	_, err := repo.CreateSet(context.Background(), workoutSet)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	var count int
	err = db.QueryRow("SELECT COUNT(*) FROM workout_sets").Scan(&count)
	if err != nil {
		t.Fatalf("Failed to get workouts: %v", err)
	}
	if count != 1 {
		t.Fatalf("Wrong number of workouts: %d", count)
	}
}
