package repository_test

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/open-workout/ow/services/workout-service/internal/domain"
	"github.com/open-workout/ow/services/workout-service/internal/infrastructure/repository"
	"github.com/testcontainers/testcontainers-go/modules/postgres"

	_ "github.com/lib/pq"
)

func setupTestDB(t *testing.T) (*sql.DB, func()) {
	ctx := context.Background()

	container, err := postgres.Run(ctx,
		"postgres:15",
		postgres.WithDatabase("test_db"),
		postgres.WithUsername("test_user"),
		postgres.WithPassword("test_password"),
	)
	if err != nil {
		t.Fatalf("Failed to start container: %v", err)
	}

	connStr, err := container.ConnectionString(ctx, "sslmode=disable")
	if err != nil {
		t.Fatalf("Failed to get connection string: %v", err)
	}

	db, err := sql.Open("postgres", connStr)
	if err != nil {
		t.Fatalf("Failed to connect: %v", err)
	}

	// IMPORTANT: retry loop instead of single ping
	deadline := time.Now().Add(10 * time.Second)

	for {
		err = db.Ping()
		if err == nil {
			break
		}

		if time.Now().After(deadline) {
			t.Fatalf("DB not ready: %v", err)
		}

		time.Sleep(200 * time.Millisecond)
	}

	cleanup := func() {
		err := db.Close()
		if err != nil {
			t.Fatalf("Failed to close DB: %v", err)
		}

		err = container.Terminate(ctx)
		if err != nil {
			t.Fatalf("Failed to terminate container: %v", err)
		}
	}

	return db, cleanup
}

func setupSchema(t *testing.T, db *sql.DB) {
	queries := []string{
		`CREATE TABLE workouts (
			workout_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id INT NOT NULL,
			title TEXT,
			started_at TIMESTAMP NOT NULL,
			finished_at TIMESTAMP
		);`,
		`CREATE TABLE workout_sets (
			set_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			workout_id INT,
			exercise_id INT,
			reps INT,
			difficulty INT,
			weight DOUBLE PRECISION,
			unit TEXT,
			logged_at TIMESTAMP
		);`,
	}

	for _, q := range queries {
		if _, err := db.Exec(q); err != nil {
			t.Fatalf("schema error: %v\nquery: %s", err, q)
		}
	}
}

// ----------------------------------
// WORKOUT tests
// ----------------------------------

func TestCreateWorkout_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)

	repo := repository.NewSqlRepository(db)

	workout := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now(),
	}

	_, err := repo.CreateWorkout(context.Background(), workout)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	var count int
	err = db.QueryRow("SELECT COUNT(*) FROM workouts").Scan(&count)
	if err != nil {
		t.Fatalf("Failed to get workouts: %v", err)
	}
	if count != 1 {
		t.Fatalf("Wrong number of workouts: %d", count)
	}

	var insertedUserID int64
	err = db.QueryRow("SELECT  user_id FROM workouts WHERE workout_id = $1", workout.WorkoutID).Scan(&insertedUserID)
	if err != nil {
		t.Fatalf("Failed to get workout: %v", err)
	}
	if insertedUserID != workout.UserID {
		t.Fatalf("Wrong workout WorkoutID: %d", insertedUserID)
	}
}

func TestGetWorkoutByID_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)
	workout := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now(),
	}

	_, err := repo.CreateWorkout(context.Background(), workout)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	newWorkout, err := repo.GetWorkoutById(context.Background(), workout.WorkoutID)
	if err != nil {
		t.Fatalf("Failed to get workout: %v", err)
	}
	if newWorkout.UserID != workout.UserID {
		t.Fatalf("Wrong workout WorkoutID: %d", newWorkout.UserID)
	}
}

// ----------------------------------
// SET tests
// ----------------------------------

func TestAllowsSetsWithSameWorkoutIDAndExerciseID_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)
	set1 := &domain.SetModel{
		WorkoutID:  100,
		ExerciseID: 1,
		Reps:       1,
		Difficulty: 2,
		Weight:     3,
		LoggedAt:   time.Now(),
	}

	set2 := &domain.SetModel{
		WorkoutID:  100,
		ExerciseID: 1,
		Reps:       1,
		Difficulty: 2,
		Weight:     3,
		LoggedAt:   time.Now(),
	}

	_, err := repo.CreateSet(context.Background(), set1)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	_, err = repo.CreateSet(context.Background(), set2)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	var count int
	err = db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE workout_id=100 AND exercise_id=1").Scan(&count)

	if count != 2 {
		t.Fatalf("Wrong number of sets: %d", count)
	}
}

func TestCreateSet_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)

	repo := repository.NewSqlRepository(db)
	workoutSet := &domain.SetModel{
		WorkoutID:  100,
		ExerciseID: 1,
		Reps:       10,
		Difficulty: 7,
		Weight:     80,
		LoggedAt:   time.Now(),
	}

	_, err := repo.CreateSet(context.Background(), workoutSet)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	var count int
	err = db.QueryRow("SELECT COUNT(*) FROM workout_sets").Scan(&count)
	if err != nil {
		t.Fatalf("Failed to get workouts: %v", err)
	}
	if count != 1 {
		t.Fatalf("Wrong number of workouts: %d", count)
	}
}

// ----------------------------------
// QUERY tests
// ----------------------------------

func TestSetFinishTime_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)
	workout := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now().Add(-1 * time.Hour),
	}

	_, err := repo.CreateWorkout(context.Background(), workout)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	err = repo.SetWorkoutFinishTime(context.Background(), workout.WorkoutID, time.Now())

	if err != nil {
		t.Fatalf("Failed to set workout finish time: %v", err)
	}

}

func TestSetFinishTimeAndGet_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now(),
	}

	_, err := repo.CreateWorkout(context.Background(), workout)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	finishTime := time.Now().UTC().Round(time.Millisecond)

	err = repo.SetWorkoutFinishTime(context.Background(), workout.WorkoutID, finishTime)

	newWorkout, err := repo.GetWorkoutById(context.Background(), workout.WorkoutID)

	if err != nil {
		t.Fatalf("Failed to get workout: %v", err)
	}

	if newWorkout.UserID != workout.UserID {
		t.Fatalf("Wrong workout WorkoutID: %d", newWorkout.UserID)
	}

	if !newWorkout.FinishedAt.Equal(finishTime) {
		t.Fatalf("Wrong finish time: %s, %s", newWorkout.FinishedAt.String(), finishTime.String())
	}
}

func TestGetLastTimeMax_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)
	workout := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now().Add(-time.Hour),
	}
	workoutResult, err := repo.CreateWorkout(context.Background(), workout)

	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	set := &domain.SetModel{
		WorkoutID:  workoutResult.WorkoutID,
		ExerciseID: 0,
		Reps:       1,
		Difficulty: 2,
		Weight:     100,
		LoggedAt:   time.Now(),
	}

	_, err = repo.CreateSet(context.Background(), set)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	err = repo.SetWorkoutFinishTime(context.Background(), workoutResult.WorkoutID, time.Now().Add(-10*time.Minute))
	if err != nil {
		t.Fatalf("Failed to set workout finish time: %v", err)
	}

	lastWeightSet, err := repo.GetLastTimeMaxSet(context.Background(), 1, 0)
	if err != nil {
		t.Fatalf("Failed to get last weight set: %v", err)
	}

	if lastWeightSet.Weight != 100 {
		t.Fatalf("Wrong last weight: %v", lastWeightSet.Weight)
	}

}

// ----------------------------------
// DELETE tests
// ----------------------------------

func TestUpdateSet_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	created, err := repo.CreateSet(context.Background(), &domain.SetModel{
		WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5, Difficulty: 3, Weight: 50, Unit: "kg",
	})
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	updated, err := repo.UpdateSet(context.Background(), 1, &domain.SetModel{
		SetID: created.SetID, Reps: 8, Difficulty: 4, Weight: 60, Unit: "kg",
	})
	if err != nil {
		t.Fatalf("Failed to update set: %v", err)
	}

	if updated.SetID != created.SetID {
		t.Fatalf("Expected same set_id, got %d", updated.SetID)
	}
	if updated.Reps != 8 {
		t.Fatalf("Expected reps=8, got %d", updated.Reps)
	}
	if updated.Weight != 60 {
		t.Fatalf("Expected weight=60, got %v", updated.Weight)
	}
	if updated.WorkoutID != workout.WorkoutID || updated.ExerciseID != 1 {
		t.Fatalf("Expected workout/exercise unchanged, got workout=%d exercise=%d", updated.WorkoutID, updated.ExerciseID)
	}
}

func TestUpdateSet_WrongUser_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	created, _ := repo.CreateSet(context.Background(), &domain.SetModel{
		WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5, Weight: 50,
	})

	_, err := repo.UpdateSet(context.Background(), 999, &domain.SetModel{
		SetID: created.SetID, Reps: 8, Weight: 60,
	})
	if err == nil {
		t.Fatal("Expected error when updating with wrong user_id, got nil")
	}

	var reps int
	db.QueryRow("SELECT reps FROM workout_sets WHERE set_id = $1", created.SetID).Scan(&reps)
	if reps != 5 {
		t.Fatalf("Expected set to be unchanged (reps=5), got reps=%d", reps)
	}
}

func TestUpdateSet_NotFound_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	_, err := repo.UpdateSet(context.Background(), 1, &domain.SetModel{
		SetID: 9999, Reps: 5, Difficulty: 3, Weight: 50, Unit: "kg",
	})
	if err == nil {
		t.Fatal("Expected error for non-existent set_id, got nil")
	}
}

func TestGetSetsByWorkoutID_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5, Weight: 50})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 2, Reps: 8, Weight: 60})

	sets, err := repo.GetSetsByWorkoutID(context.Background(), workout.WorkoutID, 1)
	if err != nil {
		t.Fatalf("Failed to get sets: %v", err)
	}
	if len(sets) != 2 {
		t.Fatalf("Expected 2 sets, got %d", len(sets))
	}
	for _, s := range sets {
		if s.WorkoutID != workout.WorkoutID {
			t.Fatalf("Expected workout_id=%d, got %d", workout.WorkoutID, s.WorkoutID)
		}
	}
}

func TestGetSetsByWorkoutID_WrongUser_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5})

	sets, err := repo.GetSetsByWorkoutID(context.Background(), workout.WorkoutID, 999)
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}
	if len(sets) != 0 {
		t.Fatalf("Expected 0 sets for wrong user, got %d", len(sets))
	}
}

// ----------------------------------
// ADMIN BYPASS tests (userId = 0)
// ----------------------------------

func TestGetSetsByWorkoutID_AdminBypass_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 42, StartedAt: time.Now()})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 2, Reps: 8})

	sets, err := repo.GetSetsByWorkoutID(context.Background(), workout.WorkoutID, 0)
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}
	if len(sets) != 2 {
		t.Fatalf("Admin bypass: expected 2 sets, got %d", len(sets))
	}
}

func TestUpdateSet_AdminBypass_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 42, StartedAt: time.Now()})
	created, _ := repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5, Weight: 50})

	updated, err := repo.UpdateSet(context.Background(), 0, &domain.SetModel{
		SetID: created.SetID, Reps: 10, Weight: 80, Unit: "kg",
	})
	if err != nil {
		t.Fatalf("Admin bypass: unexpected error: %v", err)
	}
	if updated.Reps != 10 {
		t.Fatalf("Admin bypass: expected reps=10, got %d", updated.Reps)
	}
}

func TestDeleteSet_AdminBypass_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 42, StartedAt: time.Now()})
	set, _ := repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5})

	if err := repo.DeleteSet(context.Background(), 0, set.SetID); err != nil {
		t.Fatalf("Admin bypass: unexpected error: %v", err)
	}

	var count int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE set_id = $1", set.SetID).Scan(&count)
	if count != 0 {
		t.Fatal("Admin bypass: expected set to be deleted")
	}
}

func TestDeleteWorkout_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout := &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()}
	result, err := repo.CreateWorkout(context.Background(), workout)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	_, err = repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: result.WorkoutID, ExerciseID: 1, Reps: 5, Weight: 50})
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}
	_, err = repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: result.WorkoutID, ExerciseID: 2, Reps: 5, Weight: 60})
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	if err := repo.DeleteWorkout(context.Background(), result.WorkoutID); err != nil {
		t.Fatalf("Failed to delete workout: %v", err)
	}

	var workoutCount int
	db.QueryRow("SELECT COUNT(*) FROM workouts WHERE workout_id = $1", result.WorkoutID).Scan(&workoutCount)
	if workoutCount != 0 {
		t.Fatalf("Expected workout to be deleted, got count: %d", workoutCount)
	}

	var setCount int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE workout_id = $1", result.WorkoutID).Scan(&setCount)
	if setCount != 0 {
		t.Fatalf("Expected sets to be deleted with workout, got count: %d", setCount)
	}
}

func TestDeleteWorkout_DoesNotAffectOtherWorkouts_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	w1, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	w2, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})

	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: w1.WorkoutID, ExerciseID: 1, Reps: 5})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: w2.WorkoutID, ExerciseID: 1, Reps: 5})

	if err := repo.DeleteWorkout(context.Background(), w1.WorkoutID); err != nil {
		t.Fatalf("Failed to delete workout: %v", err)
	}

	var count int
	db.QueryRow("SELECT COUNT(*) FROM workouts").Scan(&count)
	if count != 1 {
		t.Fatalf("Expected 1 remaining workout, got: %d", count)
	}

	var setCount int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets").Scan(&setCount)
	if setCount != 1 {
		t.Fatalf("Expected 1 remaining set, got: %d", setCount)
	}
}

func TestDeleteSet_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})

	set1, _ := repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5, Weight: 50})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 8, Weight: 60})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 2, Reps: 10, Weight: 40})

	if err := repo.DeleteSet(context.Background(), 1, set1.SetID); err != nil {
		t.Fatalf("Failed to delete set: %v", err)
	}

	var count int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE workout_id = $1 AND exercise_id = 1", workout.WorkoutID).Scan(&count)
	if count != 1 {
		t.Fatalf("Expected 1 remaining set for exercise 1, got: %d", count)
	}

	var remainingCount int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE workout_id = $1 AND exercise_id = 2", workout.WorkoutID).Scan(&remainingCount)
	if remainingCount != 1 {
		t.Fatalf("Expected sets for exercise 2 to remain, got: %d", remainingCount)
	}
}

func TestDeleteSet_WrongUser_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	set, _ := repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: workout.WorkoutID, ExerciseID: 1, Reps: 5})

	err := repo.DeleteSet(context.Background(), 999, set.SetID)
	if err == nil {
		t.Fatal("Expected error when deleting with wrong user_id, got nil")
	}

	var count int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE set_id = $1", set.SetID).Scan(&count)
	if count != 1 {
		t.Fatal("Expected set to still exist after failed delete")
	}
}

func TestDeleteWorkoutsByUserID_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	w1, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	w2, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 1, StartedAt: time.Now()})
	w3, _ := repo.CreateWorkout(context.Background(), &domain.WorkoutModel{UserID: 2, StartedAt: time.Now()})

	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: w1.WorkoutID, ExerciseID: 1, Reps: 5})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: w2.WorkoutID, ExerciseID: 1, Reps: 5})
	repo.CreateSet(context.Background(), &domain.SetModel{WorkoutID: w3.WorkoutID, ExerciseID: 1, Reps: 5})

	if err := repo.DeleteWorkoutsByUserID(context.Background(), 1); err != nil {
		t.Fatalf("Failed to delete workouts by user: %v", err)
	}

	var workoutCount int
	db.QueryRow("SELECT COUNT(*) FROM workouts WHERE user_id = 1").Scan(&workoutCount)
	if workoutCount != 0 {
		t.Fatalf("Expected all user 1 workouts deleted, got: %d", workoutCount)
	}

	var setCount int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE workout_id IN ($1, $2)", w1.WorkoutID, w2.WorkoutID).Scan(&setCount)
	if setCount != 0 {
		t.Fatalf("Expected sets for user 1 workouts deleted, got: %d", setCount)
	}

	var otherWorkoutCount int
	db.QueryRow("SELECT COUNT(*) FROM workouts WHERE user_id = 2").Scan(&otherWorkoutCount)
	if otherWorkoutCount != 1 {
		t.Fatalf("Expected user 2 workout to remain, got: %d", otherWorkoutCount)
	}

	var otherSetCount int
	db.QueryRow("SELECT COUNT(*) FROM workout_sets WHERE workout_id = $1", w3.WorkoutID).Scan(&otherSetCount)
	if otherSetCount != 1 {
		t.Fatalf("Expected user 2 sets to remain, got: %d", otherSetCount)
	}
}

func TestGetLastTimeMaxComplex_Postgres(t *testing.T) {
	db, cleanup := setupTestDB(t)
	t.Cleanup(cleanup)
	setupSchema(t, db)
	repo := repository.NewSqlRepository(db)

	workout1 := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now().UTC().Add(-10 * time.Hour),
	}

	workout2 := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now().UTC().Add(-5 * time.Hour),
	}

	workout3 := &domain.WorkoutModel{
		UserID:    1,
		StartedAt: time.Now().UTC().Add(-2 * time.Hour),
	}

	workoutResult1, err := repo.CreateWorkout(context.Background(), workout1)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}

	err = repo.SetWorkoutFinishTime(context.Background(), workoutResult1.WorkoutID, time.Now().UTC().Add(time.Hour))
	if err != nil {
		t.Fatalf("Failed to set workout finish time: %v", err)
	}

	workoutResult2, err := repo.CreateWorkout(context.Background(), workout2)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}
	err = repo.SetWorkoutFinishTime(context.Background(), workoutResult2.WorkoutID, time.Now().UTC().Add(time.Hour))
	if err != nil {
		t.Fatalf("Failed to set workout finish time: %v", err)
	}

	workoutResult3, err := repo.CreateWorkout(context.Background(), workout3)
	if err != nil {
		t.Fatalf("Failed to create workout: %v", err)
	}
	err = repo.SetWorkoutFinishTime(context.Background(), workoutResult3.WorkoutID, time.Now().UTC().Add(time.Hour))
	if err != nil {
		t.Fatalf("Failed to set workout finish time: %v", err)
	}

	set1 := &domain.SetModel{
		WorkoutID:  workoutResult1.WorkoutID,
		ExerciseID: 0,
		Reps:       5,
		Difficulty: 2,
		Weight:     100,
		LoggedAt:   workout1.StartedAt.Add(10 * time.Minute),
	}
	_, err = repo.CreateSet(context.Background(), set1)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	set2 := &domain.SetModel{
		WorkoutID:  workoutResult2.WorkoutID,
		ExerciseID: 0,
		Reps:       15,
		Difficulty: 2,
		Weight:     110,
		LoggedAt:   workoutResult2.StartedAt.Add(10 * time.Minute),
	}
	_, err = repo.CreateSet(context.Background(), set2)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	set3 := &domain.SetModel{
		WorkoutID:  workoutResult3.WorkoutID,
		ExerciseID: 1,
		Reps:       10,
		Difficulty: 2,
		Weight:     200,
		LoggedAt:   workoutResult3.StartedAt.Add(10 * time.Minute),
	}
	_, err = repo.CreateSet(context.Background(), set3)
	if err != nil {
		t.Fatalf("Failed to create set: %v", err)
	}

	maxSet, err := repo.GetLastTimeMaxSet(context.Background(), 1, 0)
	if err != nil {
		t.Fatalf("Failed to get max set: %v", err)
	}

	if maxSet.Weight != 110 {
		t.Fatalf("Wrong max weight: %v", maxSet.Weight)
	}

}
