apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ow
data:
  00-create-databases.sql: |
    CREATE DATABASE ow_user;
    CREATE DATABASE ow_exercise;
    CREATE DATABASE ow_workout;

  01-ow-user.sql: |
    \connect ow_user
    CREATE TABLE users
    (
        user_id     text primary key,
        email       text not null unique,
        username    text not null unique,
        sport_goals text[]    not null default '{}',
        gender      text,
        birthdate   text,
        split       jsonb     not null default '{}'
    );

  02-ow-exercise.sql: |
    \connect ow_exercise
    CREATE TABLE exercises
    (
        exercise_id       serial primary key,
        name              text,
        exercise_type     text,
        primary_muscle    text,
        secondary_muscles text[],
        description       text,
        user_id           text,
        is_private        boolean,
        weight_direction  bigint
    );
    CREATE TABLE exercise_media
    (
        exercise_id bigint,
        url         text,
        user_id     bigint,
        media_id    integer generated by default as identity
    );

  03-ow-workout.sql: |
    \connect ow_workout
    CREATE SEQUENCE workouts_workout_id_seq AS integer;
    CREATE TABLE workouts
    (
        workout_id  integer generated by default as identity primary key,
        user_id     text      not null,
        title       text,
        started_at  timestamp not null,
        finished_at timestamp
    );
    CREATE TABLE workout_sets
    (
        workout_id  integer,
        exercise_id integer,
        reps        integer,
        difficulty  integer,
        weight      double precision,
        unit        text,
        logged_at   timestamp,
        set_id      integer generated by default as identity primary key
    );
