-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

create table exercises
(
    exercise_id       serial
        primary key,
    name              text,
    exercise_type     text,
    primary_muscle    text,
    secondary_muscles text[],
    description       text,
    user_id           text,
    is_private        boolean,
    weight_direction  bigint
);

alter table exercises
    owner to vlad;

create table exercise_media
(
    exercise_id bigint,
    url         text,
    user_id     bigint,
    media_id    integer generated by default as identity
);

alter table exercise_media
    owner to vlad;

