-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

create sequence workouts_workout_id_seq
    as integer;

alter sequence workouts_workout_id_seq owner to vlad;

create table workouts
(
    workout_id  integer generated by default as identity
        primary key,
    user_id     integer   not null,
    title       text,
    started_at  timestamp not null,
    finished_at timestamp
);

alter table workouts
    owner to vlad;

create table workout_sets
(
    workout_id  integer,
    exercise_id integer,
    reps        integer,
    difficulty  integer,
    weight      double precision,
    unit        text,
    logged_at   timestamp,
    set_id      integer generated by default as identity
        primary key
);

alter table workout_sets
    owner to vlad;

