name: Workout Service CI
on:
  push:
    paths:
      - "services/workout-service/**"
  pull_request:
    paths:
      - "services/workout-service/**"
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.0"
      - name: Install dependencies
        working-directory: workout-service
        run: go mod download
      - name: Run tests
        working-directory: workout-service
        run: go test ./... -v
